[package]
name = "riddles-in-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
serde = "1.0.120"


[[bin]]
name = "rust-riddles"
path = "src/main.rs"
